SELECT ED.ID,  CASE 
                WHEN P.CNT IS NULL THEN 0
                ELSE P.CNT
                END AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CNT
            FROM ECOLI_DATA 
            GROUP BY PARENT_ID) P
ON ED.ID = P.PARENT_ID
ORDER BY 1;