SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(S.USER_ID)) AS USERS
FROM ONLINE_SALE S
LEFT JOIN USER_INFO U ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC;