WITH rent_info AS (
    SELECT RH.HISTORY_ID, 
           C.DAILY_FEE, 
           DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 AS DURATION,
           CASE 
               WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90 THEN '90일 이상'
               WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30 THEN '30일 이상'
               WHEN DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7 THEN '7일 이상'
               ELSE NULL
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR  C 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    ON RH.CAR_ID = C.CAR_ID 
    WHERE C.CAR_TYPE = '트럭'
)

SELECT RI.HISTORY_ID, ROUND(RI.DAILY_FEE * RI.DURATION * (100 - IFNULL(DP.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM rent_info RI
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON RI.DURATION_TYPE = DP.DURATION_TYPE AND DP.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;