SELECT MEMBER_NAME, REVIEW_TEXT, SUBSTR(REVIEW_DATE, 1, 10) AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID 
                    FROM REST_REVIEW 
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(REVIEW_ID) DESC
                    LIMIT 1)
ORDER BY 3 ASC, 2 ASC;