SELECT hd.DEPT_ID, hd.DEPT_NAME_EN, he.AVG_SAL
FROM HR_DEPARTMENT hd
JOIN (SELECT DEPT_ID, ROUND(AVG(SAL)) AS 'AVG_SAL' 
    FROM HR_EMPLOYEES 
    GROUP BY DEPT_ID) he
ON hd.DEPT_ID = he.DEPT_ID
ORDER BY he.AVG_SAL DESC;